title: Kyle Markwardt
logo: /assets/img/Headshot2.jpg

description: ✧ Machine Learning ✧ Engineering ✧
#show_downloads: true
theme: jekyll-theme-minimal
#themes list: [architecht, cayman, dinky, hacker, leap day, merlot, midnight, minima, minimal, modernist, slate, tactile, time machine]

# Custom CSS
sass:
  custom: 'assets/css/custom.scss'
