title: Kyle Markwardt
logo: /assets/img/Headshot1.jpg
description: Engineering ✧ Machine Learning ✧ Data Innovation
#show_downloads: true
theme: jekyll-theme-minimal
#themes list: [architecht, cayman, dinky, hacker, leap day, merlot, midnight, minima, minimal, modernist, slate, tactile, time machine]

# Custom CSS
sass:
  custom: 'assets/css/custom.scss'
